from random import randint

def data_choices():
    choices = [
        {"Name": "Instagram",
         "Occupation": "Social Media",
         "Country": "United States",
         "Fans": 517},
        {"Name": "Criatiano Ronaldo",
         "Occupation": "Football Player",
         "Country": "Portugal",
         "Fans": 452},
        {"Name": "Kyle Jenner",
         "Occupation": "MAedia Personality",
         "Country": "Unites Stares",
         "Fans": 347},
        {"Name": "Lionel Messi",
         "Occupation": "Football player",
         "Country": "Argentina",
         "Fans": 336},
        {"Name": "Selena Gomez",
         "Occupation": "Actres and singer",
         "Country": "United States",
         "Fans": 326},
        {"Name": "Dwayne Johnson",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 321},
        {"Name": "Kim Kardashian",
         "Occupation": "Media Personality",
         "Country": "United States",
         "Fans": 317},
        {"Name": "Araina Grande",
         "Occupation": "Singer and Actress",
         "Country": "United States",
         "Fans": 316},
        {"Name": "Beyonce",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 262},
        {"Name": "Kloe Kardashian",
         "Occupation": "Media Personality",
         "Country": "United States",
         "Fans": 250},
        {"Name": "Kendall Jenner",
         "Occupation": "Model",
         "Country": "United States",
         "Fans": 242},
        {"Name": "Justin Biebel",
         "Occupation": "Singer",
         "Country": "Canada",
         "Fans": 240},
        {"Name": "National Geographic",
         "Occupation": "Wildlife Magazine",
         "Country": "United States",
         "Fans": 226},
        {"Name": "Nike",
         "Occupation": "Shoes and Sportwear Company",
         "Country": "United States",
         "Fans": 222},
        {"Name": "Taylor Swift",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 214},
        {"Name": "Jennifer Lopez",
         "Occupation": "Singer and Producer",
         "Country": "Puerto Rico",
         "Fans": 212},
        {"Name": "Virat Kholi",
         "Occupation": "Cricket Player",
         "Country": "India",
         "Fans": 200},
        {"Name": "Kountney Kardashian",
         "Occupation": "Media Personality",
         "Country": "United States",
         "Fans": 183},
        {"Name": "Nicki Minaj",
         "Occupation": "Rapper",
         "Country": "Trinidad and Tobago",
         "Fans": 193},
        {"Name": "Neymar",
         "Occupation": "Football Player",
         "Country": "Brazil",
         "Fans": 175},
        {"Name": "Milley Cyrus",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 174},
        {"Name": "Katy Perry",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 163},
        {"Name": "Kevin Hart",
         "Occupation": "Comedian and Actor",
         "Country": "United States",
         "Fans": 145},
        {"Name": "Zendaya",
         "Occupation": "Actress",
         "Country": "United States",
         "Fans": 144},
        {"Name": "Demi Lovato",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 134},
        {"Name": "Cardi B",
         "Occupation": "Rapper",
         "Country": "United States",
         "Fans": 134},
        {"Name": "Rihanna",
         "Occupation": "Singer",
         "Country": "Barbados",
         "Fans": 131},
        {"Name": "Lebron James",
         "Occupation": "Basketball Player",
         "Country": "United States",
         "Fans": 123},
        {"Name": "Ellen DeGeneres",
         "Occupation": "Television Host",
         "Country": "United States",
         "Fans": 121},
        {"Name": "Real Madrid C.F.",
         "Occupation": "Football Club",
         "Country": "Spain",
         "Fans": 120},
        {"Name": "Drake",
         "Occupation": "Musician",
         "Country": "Canada",
         "Fans": "113"},
        {"Name": "F.C. Barcelona",
         "Occupation": "Football Club",
         "Country": "Spain",
         "Fans": 109},
        {"Name": "Chris Brown",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 112},
        {"Name": "Billie Ellis",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 103},
        {"Name": "UEFA Champions League",
         "Occupation": "European Football Tournament",
         "Country": "Eurpe",
         "Fans": 94.7},
        {"Name": "Dua Lipa",
         "Occupation": "Singer",
         "Country": "Albania",
         "Fans": 84.2},
        {"Name": "Vin Diesel",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 80.9},
        {"Name": "Gal Gadot",
         "Occupation": "Actress",
         "Country": "Israel",
         "Fans": 82.1},
        {"Name": "Priyanka Chopra",
         "Occupation": "Actress",
         "Country": "India",
         "Fans": 79.3},
        {"Name": "Lalisa Manoban",
         "Occupation": "Raper and Singer",
         "Country": "Thailand",
         "Fans": 78.6},
        {"Name": "NASA",
         "Occupation": "Aerospace Association",
         "Country": "United States",
         "Fans": 77.9},
        {"Name": "Khaby Lame",
         "Occupation": "Tiktoker",
         "Country": "Senegal",
         "Fans": 78.1},
        {"Name": "Shakira",
         "Occupation": "Singer",
         "Country": "Colombia",
         "Fans": 74.7},
        {"Name": "Gigi Hadid",
         "Occupation": "Model",
         "Country": "United States",
         "Fans": 74.8},
        {"Name": "Snoop Dog",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 74.1},
        {"Name": "David Beckham",
         "Occupation": "Football Player",
         "Country": "England",
         "Fans": 74},
        {"Name": "Victoria's Secret",
         "Occupation": "Female Underwear Company",
         "Country": "United States",
         "Fans": 72.8},
        {"Name": "Shraddha Kapoor",
         "Occupation": "Actress",
         "Country": "India",
         "Fans": 73},
        {"Name": "Kylian Mbappé",
         "Occupation": "Football Player",
         "Country": "France",
         "Fans": 71.7},
        {"Name": "Neka Kakkar",
         "Occupation": "Singer",
         "Country": "India",
         "Fans": 70.2},
        {"Name": "Shawn Mendez",
         "Occupation": "Singer",
         "Country": "Canada",
         "Fans": 68.8},
        {"Name": "NBA",
         "Occupation": "Bastekball Association",
         "Country": "United States",
         "Fans": 67.9},
        {"Name": "Deepika Padukone",
         "Occupation": "Actress",
         "Country": "India",
         "Fans": 67.4},
        {"Name": "Kim Jennie",
         "Occupation": "Singer",
         "Country": "South Korea",
         "Fans": 67.3},
        {"Name": "Emma Watson",
         "Occupation": "Actress",
         "Country": "England",
         "Fans": 66.8},
        {"Name": "Ronaldo de Assis Moreira",
         "Occupation": "Football Player",
         "Country": "Brazil",
         "Fans": 66.9},
        {"Name": "Alia Bhatt",
         "Occupation": "Actress",
         "Country": "United Kingdom",
         "Fans": 66.3},
        {"Name": "Katrina Kaif",
         "Occupation": "Actress",
         "Country": "United Kingdom",
         "Fans": 65.2},
        {"Name": "Justin Timberlake",
         "Occupation": "Singer",
         "Country": "United States",
         "Fans": 65.1},
        {"Name": "Marvel Entertainment",
         "Occupation": "Movies and TV series company",
         "Country": "United States",
         "Fans": 65},
        {"Name": "BTS",
         "Occupation": "Pop music group",
         "Country": "South Korea",
         "Fans": 64.9},
        {"Name": "Will Smith",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 64.4},
        {"Name": "Camila Cabello",
         "Occupation": "Singer",
         "Country": "Cuba",
         "Fans": 63.6},
        {"Name": "Maluma",
         "Occupation": "Singer",
         "Country": "Colombia",
         "Fans": 62.5},
        {"Name": "Anitta",
         "Occupation": "Singer",
         "Country": "Brazil",
         "Fans": 62.6},
        {"Name": "Akshay Kumar",
         "Occupation": "Actor and Producer",
         "Country": "India",
         "Fans": 62.4},
        {"Name": "Raffi Ahmad and Nagita Slavina",
         "Occupation": "Actors and Singers",
         "Country": "Indonesia",
         "Fans": 62.3},
        {"Name": "Jaqueline Fernandez",
         "Occupation": "Actress",
         "Country": "Sri-Lanka",
         "Fans": 61.5},
        {"Name": "Kim Ji-soo",
         "Occupation": "Singer and Actress",
         "Country": "South Korea",
         "Fans": 61.2},
        {"Name": "Paris Saint-Germain",
         "Occupation": "Football Club",
         "Country": "France",
         "Fans": 60.6},
        {"Name": "Roseanne Park",
         "Occupation": "Singer",
         "Country": "New Zealand",
         "Fans": 60},
        {"Name": "Anushka Sharma",
         "Occupation": "Actress",
         "Country": "India",
         "Fans": 58.9},
        {"Name": "Manchester United",
         "Occupation": "Football Club",
         "Country": "England",
         "Fans": ""},
        {"Name": "Whindersson Nunes",
         "Occupation": "Youtuber",
         "Country": "Brazil",
         "Fans": 58.4},
        {"Name": "9GAG",
         "Occupation": "Social Media Website",
         "Country": "China",
         "Fans": 58.2},
        {"Name": "Premier League",
         "Occupation": "English Football League",
         "Country": "England",
         "Fans": 57.4},
        {"Name": "Marcelo Vieira Jr.",
         "Occupation": "Football Player",
         "Country": "Brazil",
         "Fans": 56.3},
        {"Name": "Chris Hermsworth",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 54.8},
        {"Name": "Paul Labile Pogba",
         "Occupation": "Football player",
         "Country": "France",
         "Fans": 54.2},
        {"Name": "Zlatan Ibrahimovic",
         "Occupation": "Football Player",
         "Country": "Sweden",
         "Fans": 54.1},
        {"Name": "Leonardo DiCaprio",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 53.8},
        {"Name": "Juventus",
         "Occupation": "Football Club",
         "Country": "Italy",
         "Fans": 53.7},
        {"Name": "Karol G",
         "Occupation": "Singer",
         "Country": "Colombia",
         "Fans": 53.5},
        {"Name": "Zac Efron",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 53.4},
        {"Name": "Tata Werneck",
         "Occupation": "Actress",
         "Country": "Brazil",
         "Fans": 53.2},
        {"Name": "Robert Downey Jr.",
         "Occupation": "Actor",
         "Country": "United States",
         "Fans": 53.1},
        {"Name": "Lady Gaga",
         "Occupation": "Singer",
         "Country": "France",
         "Fans": 52.8},
        {"Name": "Sunny Leone",
         "Occupation": "Porn Actress",
         "Country": "Canada",
         "Fans": 52.9},
        {"Name": "J Balvin",
         "Occupation": "Singer",
         "Country": "Colombia",
         "Fans": 52.6},
        {"Name": "Bella Hadid",
         "Occupation": "Model",
         "Country": "United States",
         "Fans": 52.7},
        {"Name": "Salman Khan",
         "Occupation": "Actor",
         "Country": "India",
         "Fans": 52.4},
        {"Name": "Ayu Ting Ting",
         "Occupation": "Singer",
         "Country": "Indonesia",
         "Fans": 51.9},
        {"Name": "Sergio Ramos",
         "Occupation": "Football Player",
         "Country": "Spain",
         "Fans": 51.7},
        {"Name": "Disha Patani",
         "Occupation": "Actress",
         "Country": "India",
         "Fans": 51.6},
        {"Name": "Huda Kattan",
         "Occupation": "Makeover artist",
         "Country": "United States",
         "Fans": 50.5},
        {"Name": "ZARA",
         "Occupation": "Clothes Enterprise",
         "Country": "Spain",
         "Fans": 51.2},
        {"Name": "CHANNEL",
         "Occupation": "Perfume Enterprise",
         "Country": "France",
         "Fans": 50.8},
        {"Name": "Adele",
         "Occupation": "Singer",
         "Country": "England",
         "Fans": 50.2},
        {"Name": "Mohamed Salah",
         "Occupation": "Football Player",
         "Country": "Egypt",
         "Fans": 51.2},
        {"Name": "Karim Benzema",
         "Occupation": "Football Player",
         "Country": "France",
         "Fans": 54.6},
    ]
    random_choice = choices[randint(0,99)]
    return random_choice
